# -*- coding: utf-8 -*-
"""SimplePY.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15v-d_vRS7jKD1AT6yc-gBMNFtvjdrfe7
"""

import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a.shape)
print(a.dtype)

b = np.zeros(5)
print(b)

c = np.zeros((2,4))
print(c)
print(len(c))
print(c.size)
print(c.shape)
print(c.dtype)

"""Return an array of zeros with the same shape and type as a given array.

numpy.matlib.empty()La fonction renvoie une nouvelle matrice de forme et de type donnés, sans initialiser les entrées.

linspace(x1, x2) renvoie un vecteur ligne de n valeurs régulièrement espacées entre x1 et x2

arange() retourne un tableau à la différence de range()
"""

d = np.random.rand(5)
print(d)
e = np.random.rand(3,3)
print(e)
print(d.shape)
print(e.shape)

"""### EXO 2"""

x = np.linspace(0, 2*np.pi, 100)
sin_x = np.sin(x)
cos_x = np.cos(x)
log_x = np.log(x[1:])  # Avoid log(0)

f1 = sin_x * cos_x
f2 = cos_x**2 - sin_x**2

sin_x += 1.5

"""dot: product of two arrays.      
@: Matrix multiplication for two arrays.
"""